pipeline {
    agent any

    stages {
        stage('git') {
            steps {
                sh '''
                    ansible all -a 'whoami'
                '''
            }
        }

    }
}
