pipeline {
    agent any

    stages {
        stage('git') {
            steps {
               ansiblePlaybook becomeUser: null, credentialsId: '36cbbbd9-cc83-47ef-976c-53ea9ee922e9', installation: 'ansible', inventory: 'myapp-ansible-master/dev.inv', playbook: 'myapp-ansible-master/apache.yml', sudoUser: null
               
            }
        }

    }
}
